version : 0.0.3
container-name-run : "tmp-swift-run"
container-name-tools : "tmp-swift-tools"
image-name-run : "tmp-swiftrun"
image-name-tools: "tmp-swifttools"
dockerfile-tools: "Dockerfile-tools"
dockerfile-run: "Dockerfile"
build-cmd-debug : "/swift-utils/tools-utils.sh build debug"
debug-cmd : "/swift-utils/tools-utils.sh debug tmp 1024"
build-cmd-run : "/swift-utils/tools-utils.sh build release"
run-cmd : ""
test-cmd : "/swift-utils/tools-utils.sh test"
container-path-run : "/swift-project"
container-path-tools : "/swift-project"
container-port-map : "8080:8080"
container-port-map-debug : "2048:1024,2049:1025"
chart-path : "chart/tmp"
